//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataAccess.ProcessModule.UnitOfWork
{
    using System.Data.Entity;
    using Core.Entities.Process;
    using Data.Common.Definition;
    
    public partial interface IProcessContext : IQueryableUnitOfWork
    {
        DbSet<Execution> Execution { get; set; }
        DbSet<ExecutionApplicant> ExecutionApplicant { get; set; }
        DbSet<ExecutionStep> ExecutionStep { get; set; }
        DbSet<ExtendedDataList> ExtendedDataList { get; set; }
        DbSet<ExtendedField> ExtendedField { get; set; }
        DbSet<ExtendedFieldValue> ExtendedFieldValue { get; set; }
        DbSet<ExtendedFile> ExtendedFile { get; set; }
        DbSet<ExtendedList> ExtendedList { get; set; }
        DbSet<FieldInSection> FieldInSection { get; set; }
        DbSet<Page> Page { get; set; }
        DbSet<Process> Process { get; set; }
        DbSet<Product> Product { get; set; }
        DbSet<ProductProcess> ProductProcess { get; set; }
        DbSet<Section> Section { get; set; }
        DbSet<State> State { get; set; }
        DbSet<Step> Step { get; set; }
        DbSet<StepSection> StepSection { get; set; }
        DbSet<WebServiceConsultation> WebServiceConsultation { get; set; }
    }
}
