//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtendedField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExtendedField()
        {
            this.ExtendedFieldValue = new HashSet<ExtendedFieldValue>();
            this.FieldInSection = new HashSet<FieldInSection>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int BaseFieldId { get; set; }
        public int DataType { get; set; }
        public string ClientValidationClass { get; set; }
        public Nullable<int> ListId { get; set; }
        public int ProcessId { get; set; }
        public string HtmlData { get; set; }
        public string NameService { get; set; }
    
        public virtual ExtendedList ExtendedList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtendedFieldValue> ExtendedFieldValue { get; set; }
        public virtual Process Process { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FieldInSection> FieldInSection { get; set; }
    }
}
