//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Data.DataCredito.EvidenteService
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioIdentificacionSoapBinding", Namespace="http://www.datacredito.com.co/services/ServicioIdentificacion")]
    public partial class ServicioIdentificacion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback consultarTiposAlertaOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarAlertasOperationCompleted;
        
        private System.Threading.SendOrPostCallback validarOperationCompleted;
        
        private System.Threading.SendOrPostCallback preguntasOperationCompleted;
        
        private System.Threading.SendOrPostCallback verificarOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarParametroOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarParametrizacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarParametrizacionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarParametrizacionesCompletasOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarCodigosValidacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarCodigosPreguntasOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarParametroParametrizacionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarParametroParametrizaciones1OperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarUltimoResultadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarSistemaAlertasOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarEstadisticasDetalladasOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarListaEstadisticasGeneradasOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarListaEstadisticasEncuestasGeneradasOperationCompleted;
        
        private System.Threading.SendOrPostCallback adicionarRespuestaCuestionarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarEstadisticasEncuestasDetalladasOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicioIdentificacion() {
            this.Url = global::Data.DataCredito.Properties.Settings.Default.Data_DataCredito_EvidenteService_ServicioIdentificacion;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event consultarTiposAlertaCompletedEventHandler consultarTiposAlertaCompleted;
        
        /// <remarks/>
        public event consultarAlertasCompletedEventHandler consultarAlertasCompleted;
        
        /// <remarks/>
        public event validarCompletedEventHandler validarCompleted;
        
        /// <remarks/>
        public event preguntasCompletedEventHandler preguntasCompleted;
        
        /// <remarks/>
        public event verificarCompletedEventHandler verificarCompleted;
        
        /// <remarks/>
        public event consultarParametroCompletedEventHandler consultarParametroCompleted;
        
        /// <remarks/>
        public event consultarParametrizacionCompletedEventHandler consultarParametrizacionCompleted;
        
        /// <remarks/>
        public event consultarParametrizacionesCompletedEventHandler consultarParametrizacionesCompleted;
        
        /// <remarks/>
        public event consultarParametrizacionesCompletasCompletedEventHandler consultarParametrizacionesCompletasCompleted;
        
        /// <remarks/>
        public event consultarCodigosValidacionCompletedEventHandler consultarCodigosValidacionCompleted;
        
        /// <remarks/>
        public event consultarCodigosPreguntasCompletedEventHandler consultarCodigosPreguntasCompleted;
        
        /// <remarks/>
        public event consultarParametroParametrizacionesCompletedEventHandler consultarParametroParametrizacionesCompleted;
        
        /// <remarks/>
        public event consultarParametroParametrizaciones1CompletedEventHandler consultarParametroParametrizaciones1Completed;
        
        /// <remarks/>
        public event consultarUltimoResultadoCompletedEventHandler consultarUltimoResultadoCompleted;
        
        /// <remarks/>
        public event consultarSistemaAlertasCompletedEventHandler consultarSistemaAlertasCompleted;
        
        /// <remarks/>
        public event consultarEstadisticasDetalladasCompletedEventHandler consultarEstadisticasDetalladasCompleted;
        
        /// <remarks/>
        public event consultarListaEstadisticasGeneradasCompletedEventHandler consultarListaEstadisticasGeneradasCompleted;
        
        /// <remarks/>
        public event consultarListaEstadisticasEncuestasGeneradasCompletedEventHandler consultarListaEstadisticasEncuestasGeneradasCompleted;
        
        /// <remarks/>
        public event adicionarRespuestaCuestionarioCompletedEventHandler adicionarRespuestaCuestionarioCompleted;
        
        /// <remarks/>
        public event consultarEstadisticasEncuestasDetalladasCompletedEventHandler consultarEstadisticasEncuestasDetalladasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.id.dc.com", ResponseNamespace="http://www.datacredito.com.co/services/ServicioIdentificacion")]
        [return: System.Xml.Serialization.SoapElementAttribute("consultarTiposAlertaReturn")]
        public string consultarTiposAlerta(string criteriosXML) {
            object[] results = this.Invoke("consultarTiposAlerta", new object[] {
                        criteriosXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultarTiposAlertaAsync(string criteriosXML) {
            this.consultarTiposAlertaAsync(criteriosXML, null);
        }
        
        /// <remarks/>
        public void consultarTiposAlertaAsync(string criteriosXML, object userState) {
            if ((this.consultarTiposAlertaOperationCompleted == null)) {
                this.consultarTiposAlertaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarTiposAlertaOperationCompleted);
            }
            this.InvokeAsync("consultarTiposAlerta", new object[] {
                        criteriosXML}, this.consultarTiposAlertaOperationCompleted, userState);
        }
        
        private void OnconsultarTiposAlertaOperationCompleted(object arg) {
            if ((this.consultarTiposAlertaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarTiposAlertaCompleted(this, new consultarTiposAlertaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.id.dc.com", ResponseNamespace="http://www.datacredito.com.co/services/ServicioIdentificacion")]
        [return: System.Xml.Serialization.SoapElementAttribute("consultarAlertasReturn")]
        public string consultarAlertas(string tipoDoc, string numDoc) {
            object[] results = this.Invoke("consultarAlertas", new object[] {
                        tipoDoc,
                        numDoc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultarAlertasAsync(string tipoDoc, string numDoc) {
            this.consultarAlertasAsync(tipoDoc, numDoc, null);
        }
        
        /// <remarks/>
        public void consultarAlertasAsync(string tipoDoc, string numDoc, object userState) {
            if ((this.consultarAlertasOperationCompleted == null)) {
                this.consultarAlertasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarAlertasOperationCompleted);
            }
            this.InvokeAsync("consultarAlertas", new object[] {
                        tipoDoc,
                        numDoc}, this.consultarAlertasOperationCompleted, userState);
        }
        
        private void OnconsultarAlertasOperationCompleted(object arg) {
            if ((this.consultarAlertasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarAlertasCompleted(this, new consultarAlertasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.id.dc.com", ResponseNamespace="http://www.datacredito.com.co/services/ServicioIdentificacion")]
        [return: System.Xml.Serialization.SoapElementAttribute("validarReturn")]
        public string validar(string paramProducto, string producto, string canal, string datosValidacion) {
            object[] results = this.Invoke("validar", new object[] {
                        paramProducto,
                        producto,
                        canal,
                        datosValidacion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void validarAsync(string paramProducto, string producto, string canal, string datosValidacion) {
            this.validarAsync(paramProducto, producto, canal, datosValidacion, null);
        }
        
        /// <remarks/>
        public void validarAsync(string paramProducto, string producto, string canal, string datosValidacion, object userState) {
            if ((this.validarOperationCompleted == null)) {
                this.validarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidarOperationCompleted);
            }
            this.InvokeAsync("validar", new object[] {
                        paramProducto,
                        producto,
                        canal,
                        datosValidacion}, this.validarOperationCompleted, userState);
        }
        
        private void OnvalidarOperationCompleted(object arg) {
            if ((this.validarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validarCompleted(this, new validarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.id.dc.com", ResponseNamespace="http://www.datacredito.com.co/services/ServicioIdentificacion")]
        [return: System.Xml.Serialization.SoapElementAttribute("preguntasReturn")]
        public string preguntas(string paramProducto, string producto, string canal, string solicitudCuestionario) {
            object[] results = this.Invoke("preguntas", new object[] {
                        paramProducto,
                        producto,
                        canal,
                        solicitudCuestionario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void preguntasAsync(string paramProducto, string producto, string canal, string solicitudCuestionario) {
            this.preguntasAsync(paramProducto, producto, canal, solicitudCuestionario, null);
        }
        
        /// <remarks/>
        public void preguntasAsync(string paramProducto, string producto, string canal, string solicitudCuestionario, object userState) {
            if ((this.preguntasOperationCompleted == null)) {
                this.preguntasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpreguntasOperationCompleted);
            }
            this.InvokeAsync("preguntas", new object[] {
                        paramProducto,
                        producto,
                        canal,
                        solicitudCuestionario}, this.preguntasOperationCompleted, userState);
        }
        
        private void OnpreguntasOperationCompleted(object arg) {
            if ((this.preguntasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.preguntasCompleted(this, new preguntasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.id.dc.com", ResponseNamespace="http://www.datacredito.com.co/services/ServicioIdentificacion")]
        [return: System.Xml.Serialization.SoapElementAttribute("verificarReturn")]
        public string verificar(string producto, string paramProducto, string respuestas) {
            object[] results = this.Invoke("verificar", new object[] {
                        producto,
                        paramProducto,
                        respuestas});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void verificarAsync(string producto, string paramProducto, string respuestas) {
            this.verificarAsync(producto, paramProducto, respuestas, null);
        }
        
        /// <remarks/>
        public void verificarAsync(string producto, string paramProducto, string respuestas, object userState) {
            if ((this.verificarOperationCompleted == null)) {
                this.verificarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverificarOperationCompleted);
            }
            this.InvokeAsync("verificar", new object[] {
                        producto,
                        paramProducto,
                        respuestas}, this.verificarOperationCompleted, userState);
        }
        
        private void OnverificarOperationCompleted(object arg) {
            if ((this.verificarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verificarCompleted(this, new verificarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.id.dc.com", ResponseNamespace="http://www.datacredito.com.co/services/ServicioIdentificacion")]
        [return: System.Xml.Serialization.SoapElementAttribute("consultarParametroReturn")]
        public string consultarParametro(string parametrizacion, string transaccion, string producto, string parametro) {
            object[] results = this.Invoke("consultarParametro", new object[] {
                        parametrizacion,
                        transaccion,
                        producto,
                        parametro});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultarParametroAsync(string parametrizacion, string transaccion, string producto, string parametro) {
            this.consultarParametroAsync(parametrizacion, transaccion, producto, parametro, null);
        }
        
        /// <remarks/>
        public void consultarParametroAsync(string parametrizacion, string transaccion, string producto, string parametro, object userState) {
            if ((this.consultarParametroOperationCompleted == null)) {
                this.consultarParametroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarParametroOperationCompleted);
            }
            this.InvokeAsync("consultarParametro", new object[] {
                        parametrizacion,
                        transaccion,
                        producto,
                        parametro}, this.consultarParametroOperationCompleted, userState);
        }
        
        private void OnconsultarParametroOperationCompleted(object arg) {
            if ((this.consultarParametroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarParametroCompleted(this, new consultarParametroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.id.dc.com", ResponseNamespace="http://www.datacredito.com.co/services/ServicioIdentificacion")]
        [return: System.Xml.Serialization.SoapElementAttribute("consultarParametrizacionReturn")]
        public string consultarParametrizacion(string producto, string consecutivo, string nit) {
            object[] results = this.Invoke("consultarParametrizacion", new object[] {
                        producto,
                        consecutivo,
                        nit});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultarParametrizacionAsync(string producto, string consecutivo, string nit) {
            this.consultarParametrizacionAsync(producto, consecutivo, nit, null);
        }
        
        /// <remarks/>
        public void consultarParametrizacionAsync(string producto, string consecutivo, string nit, object userState) {
            if ((this.consultarParametrizacionOperationCompleted == null)) {
                this.consultarParametrizacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarParametrizacionOperationCompleted);
            }
            this.InvokeAsync("consultarParametrizacion", new object[] {
                        producto,
                        consecutivo,
                        nit}, this.consultarParametrizacionOperationCompleted, userState);
        }
        
        private void OnconsultarParametrizacionOperationCompleted(object arg) {
            if ((this.consultarParametrizacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarParametrizacionCompleted(this, new consultarParametrizacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.id.dc.com", ResponseNamespace="http://www.datacredito.com.co/services/ServicioIdentificacion")]
        [return: System.Xml.Serialization.SoapElementAttribute("consultarParametrizacionesReturn")]
        public string consultarParametrizaciones(string producto, string tipoIdentificacion, string entidad) {
            object[] results = this.Invoke("consultarParametrizaciones", new object[] {
                        producto,
                        tipoIdentificacion,
                        entidad});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultarParametrizacionesAsync(string producto, string tipoIdentificacion, string entidad) {
            this.consultarParametrizacionesAsync(producto, tipoIdentificacion, entidad, null);
        }
        
        /// <remarks/>
        public void consultarParametrizacionesAsync(string producto, string tipoIdentificacion, string entidad, object userState) {
            if ((this.consultarParametrizacionesOperationCompleted == null)) {
                this.consultarParametrizacionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarParametrizacionesOperationCompleted);
            }
            this.InvokeAsync("consultarParametrizaciones", new object[] {
                        producto,
                        tipoIdentificacion,
                        entidad}, this.consultarParametrizacionesOperationCompleted, userState);
        }
        
        private void OnconsultarParametrizacionesOperationCompleted(object arg) {
            if ((this.consultarParametrizacionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarParametrizacionesCompleted(this, new consultarParametrizacionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.id.dc.com", ResponseNamespace="http://www.datacredito.com.co/services/ServicioIdentificacion")]
        [return: System.Xml.Serialization.SoapElementAttribute("consultarParametrizacionesCompletasReturn")]
        public string consultarParametrizacionesCompletas(string producto, string tipoIdentificacion, string entidad, bool indParametros) {
            object[] results = this.Invoke("consultarParametrizacionesCompletas", new object[] {
                        producto,
                        tipoIdentificacion,
                        entidad,
                        indParametros});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultarParametrizacionesCompletasAsync(string producto, string tipoIdentificacion, string entidad, bool indParametros) {
            this.consultarParametrizacionesCompletasAsync(producto, tipoIdentificacion, entidad, indParametros, null);
        }
        
        /// <remarks/>
        public void consultarParametrizacionesCompletasAsync(string producto, string tipoIdentificacion, string entidad, bool indParametros, object userState) {
            if ((this.consultarParametrizacionesCompletasOperationCompleted == null)) {
                this.consultarParametrizacionesCompletasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarParametrizacionesCompletasOperationCompleted);
            }
            this.InvokeAsync("consultarParametrizacionesCompletas", new object[] {
                        producto,
                        tipoIdentificacion,
                        entidad,
                        indParametros}, this.consultarParametrizacionesCompletasOperationCompleted, userState);
        }
        
        private void OnconsultarParametrizacionesCompletasOperationCompleted(object arg) {
            if ((this.consultarParametrizacionesCompletasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarParametrizacionesCompletasCompleted(this, new consultarParametrizacionesCompletasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.id.dc.com", ResponseNamespace="http://www.datacredito.com.co/services/ServicioIdentificacion")]
        [return: System.Xml.Serialization.SoapElementAttribute("consultarCodigosValidacionReturn")]
        public string consultarCodigosValidacion() {
            object[] results = this.Invoke("consultarCodigosValidacion", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultarCodigosValidacionAsync() {
            this.consultarCodigosValidacionAsync(null);
        }
        
        /// <remarks/>
        public void consultarCodigosValidacionAsync(object userState) {
            if ((this.consultarCodigosValidacionOperationCompleted == null)) {
                this.consultarCodigosValidacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarCodigosValidacionOperationCompleted);
            }
            this.InvokeAsync("consultarCodigosValidacion", new object[0], this.consultarCodigosValidacionOperationCompleted, userState);
        }
        
        private void OnconsultarCodigosValidacionOperationCompleted(object arg) {
            if ((this.consultarCodigosValidacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarCodigosValidacionCompleted(this, new consultarCodigosValidacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.id.dc.com", ResponseNamespace="http://www.datacredito.com.co/services/ServicioIdentificacion")]
        [return: System.Xml.Serialization.SoapElementAttribute("consultarCodigosPreguntasReturn")]
        public string consultarCodigosPreguntas() {
            object[] results = this.Invoke("consultarCodigosPreguntas", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultarCodigosPreguntasAsync() {
            this.consultarCodigosPreguntasAsync(null);
        }
        
        /// <remarks/>
        public void consultarCodigosPreguntasAsync(object userState) {
            if ((this.consultarCodigosPreguntasOperationCompleted == null)) {
                this.consultarCodigosPreguntasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarCodigosPreguntasOperationCompleted);
            }
            this.InvokeAsync("consultarCodigosPreguntas", new object[0], this.consultarCodigosPreguntasOperationCompleted, userState);
        }
        
        private void OnconsultarCodigosPreguntasOperationCompleted(object arg) {
            if ((this.consultarCodigosPreguntasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarCodigosPreguntasCompleted(this, new consultarCodigosPreguntasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.id.dc.com", ResponseNamespace="http://www.datacredito.com.co/services/ServicioIdentificacion")]
        [return: System.Xml.Serialization.SoapElementAttribute("consultarParametroParametrizacionesReturn")]
        public string consultarParametroParametrizaciones(string parametrizacionesXML, string transaccion, string codParametro) {
            object[] results = this.Invoke("consultarParametroParametrizaciones", new object[] {
                        parametrizacionesXML,
                        transaccion,
                        codParametro});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultarParametroParametrizacionesAsync(string parametrizacionesXML, string transaccion, string codParametro) {
            this.consultarParametroParametrizacionesAsync(parametrizacionesXML, transaccion, codParametro, null);
        }
        
        /// <remarks/>
        public void consultarParametroParametrizacionesAsync(string parametrizacionesXML, string transaccion, string codParametro, object userState) {
            if ((this.consultarParametroParametrizacionesOperationCompleted == null)) {
                this.consultarParametroParametrizacionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarParametroParametrizacionesOperationCompleted);
            }
            this.InvokeAsync("consultarParametroParametrizaciones", new object[] {
                        parametrizacionesXML,
                        transaccion,
                        codParametro}, this.consultarParametroParametrizacionesOperationCompleted, userState);
        }
        
        private void OnconsultarParametroParametrizacionesOperationCompleted(object arg) {
            if ((this.consultarParametroParametrizacionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarParametroParametrizacionesCompleted(this, new consultarParametroParametrizacionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="consultarParametroParametrizaciones1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.id.dc.com", ResponseNamespace="http://www.datacredito.com.co/services/ServicioIdentificacion")]
        [return: System.Xml.Serialization.SoapElementAttribute("consultarParametroParametrizacionesReturn")]
        public string consultarParametroParametrizaciones(string parametrizacionesXML, string codParametro) {
            object[] results = this.Invoke("consultarParametroParametrizaciones1", new object[] {
                        parametrizacionesXML,
                        codParametro});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultarParametroParametrizaciones1Async(string parametrizacionesXML, string codParametro) {
            this.consultarParametroParametrizaciones1Async(parametrizacionesXML, codParametro, null);
        }
        
        /// <remarks/>
        public void consultarParametroParametrizaciones1Async(string parametrizacionesXML, string codParametro, object userState) {
            if ((this.consultarParametroParametrizaciones1OperationCompleted == null)) {
                this.consultarParametroParametrizaciones1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarParametroParametrizaciones1OperationCompleted);
            }
            this.InvokeAsync("consultarParametroParametrizaciones1", new object[] {
                        parametrizacionesXML,
                        codParametro}, this.consultarParametroParametrizaciones1OperationCompleted, userState);
        }
        
        private void OnconsultarParametroParametrizaciones1OperationCompleted(object arg) {
            if ((this.consultarParametroParametrizaciones1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarParametroParametrizaciones1Completed(this, new consultarParametroParametrizaciones1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.id.dc.com", ResponseNamespace="http://www.datacredito.com.co/services/ServicioIdentificacion")]
        [return: System.Xml.Serialization.SoapElementAttribute("consultarUltimoResultadoReturn")]
        public string consultarUltimoResultado(string producto, string nit, string tipo_identificacion, string identificacion) {
            object[] results = this.Invoke("consultarUltimoResultado", new object[] {
                        producto,
                        nit,
                        tipo_identificacion,
                        identificacion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultarUltimoResultadoAsync(string producto, string nit, string tipo_identificacion, string identificacion) {
            this.consultarUltimoResultadoAsync(producto, nit, tipo_identificacion, identificacion, null);
        }
        
        /// <remarks/>
        public void consultarUltimoResultadoAsync(string producto, string nit, string tipo_identificacion, string identificacion, object userState) {
            if ((this.consultarUltimoResultadoOperationCompleted == null)) {
                this.consultarUltimoResultadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarUltimoResultadoOperationCompleted);
            }
            this.InvokeAsync("consultarUltimoResultado", new object[] {
                        producto,
                        nit,
                        tipo_identificacion,
                        identificacion}, this.consultarUltimoResultadoOperationCompleted, userState);
        }
        
        private void OnconsultarUltimoResultadoOperationCompleted(object arg) {
            if ((this.consultarUltimoResultadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarUltimoResultadoCompleted(this, new consultarUltimoResultadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.id.dc.com", ResponseNamespace="http://www.datacredito.com.co/services/ServicioIdentificacion")]
        [return: System.Xml.Serialization.SoapElementAttribute("consultarSistemaAlertasReturn")]
        public string consultarSistemaAlertas(string producto, string nit, string paramProducto) {
            object[] results = this.Invoke("consultarSistemaAlertas", new object[] {
                        producto,
                        nit,
                        paramProducto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultarSistemaAlertasAsync(string producto, string nit, string paramProducto) {
            this.consultarSistemaAlertasAsync(producto, nit, paramProducto, null);
        }
        
        /// <remarks/>
        public void consultarSistemaAlertasAsync(string producto, string nit, string paramProducto, object userState) {
            if ((this.consultarSistemaAlertasOperationCompleted == null)) {
                this.consultarSistemaAlertasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarSistemaAlertasOperationCompleted);
            }
            this.InvokeAsync("consultarSistemaAlertas", new object[] {
                        producto,
                        nit,
                        paramProducto}, this.consultarSistemaAlertasOperationCompleted, userState);
        }
        
        private void OnconsultarSistemaAlertasOperationCompleted(object arg) {
            if ((this.consultarSistemaAlertasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarSistemaAlertasCompleted(this, new consultarSistemaAlertasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.id.dc.com", ResponseNamespace="http://www.datacredito.com.co/services/ServicioIdentificacion")]
        [return: System.Xml.Serialization.SoapElementAttribute("consultarEstadisticasDetalladasReturn")]
        public string consultarEstadisticasDetalladas(string xmlEstadisticasDetalldas, string email) {
            object[] results = this.Invoke("consultarEstadisticasDetalladas", new object[] {
                        xmlEstadisticasDetalldas,
                        email});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultarEstadisticasDetalladasAsync(string xmlEstadisticasDetalldas, string email) {
            this.consultarEstadisticasDetalladasAsync(xmlEstadisticasDetalldas, email, null);
        }
        
        /// <remarks/>
        public void consultarEstadisticasDetalladasAsync(string xmlEstadisticasDetalldas, string email, object userState) {
            if ((this.consultarEstadisticasDetalladasOperationCompleted == null)) {
                this.consultarEstadisticasDetalladasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarEstadisticasDetalladasOperationCompleted);
            }
            this.InvokeAsync("consultarEstadisticasDetalladas", new object[] {
                        xmlEstadisticasDetalldas,
                        email}, this.consultarEstadisticasDetalladasOperationCompleted, userState);
        }
        
        private void OnconsultarEstadisticasDetalladasOperationCompleted(object arg) {
            if ((this.consultarEstadisticasDetalladasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarEstadisticasDetalladasCompleted(this, new consultarEstadisticasDetalladasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.id.dc.com", ResponseNamespace="http://www.datacredito.com.co/services/ServicioIdentificacion")]
        [return: System.Xml.Serialization.SoapElementAttribute("consultarListaEstadisticasGeneradasReturn")]
        public string consultarListaEstadisticasGeneradas(string entidad, string identificacion) {
            object[] results = this.Invoke("consultarListaEstadisticasGeneradas", new object[] {
                        entidad,
                        identificacion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultarListaEstadisticasGeneradasAsync(string entidad, string identificacion) {
            this.consultarListaEstadisticasGeneradasAsync(entidad, identificacion, null);
        }
        
        /// <remarks/>
        public void consultarListaEstadisticasGeneradasAsync(string entidad, string identificacion, object userState) {
            if ((this.consultarListaEstadisticasGeneradasOperationCompleted == null)) {
                this.consultarListaEstadisticasGeneradasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarListaEstadisticasGeneradasOperationCompleted);
            }
            this.InvokeAsync("consultarListaEstadisticasGeneradas", new object[] {
                        entidad,
                        identificacion}, this.consultarListaEstadisticasGeneradasOperationCompleted, userState);
        }
        
        private void OnconsultarListaEstadisticasGeneradasOperationCompleted(object arg) {
            if ((this.consultarListaEstadisticasGeneradasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarListaEstadisticasGeneradasCompleted(this, new consultarListaEstadisticasGeneradasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.id.dc.com", ResponseNamespace="http://www.datacredito.com.co/services/ServicioIdentificacion")]
        [return: System.Xml.Serialization.SoapElementAttribute("consultarListaEstadisticasEncuestasGeneradasReturn")]
        public string consultarListaEstadisticasEncuestasGeneradas(string entidad, string identificacion) {
            object[] results = this.Invoke("consultarListaEstadisticasEncuestasGeneradas", new object[] {
                        entidad,
                        identificacion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultarListaEstadisticasEncuestasGeneradasAsync(string entidad, string identificacion) {
            this.consultarListaEstadisticasEncuestasGeneradasAsync(entidad, identificacion, null);
        }
        
        /// <remarks/>
        public void consultarListaEstadisticasEncuestasGeneradasAsync(string entidad, string identificacion, object userState) {
            if ((this.consultarListaEstadisticasEncuestasGeneradasOperationCompleted == null)) {
                this.consultarListaEstadisticasEncuestasGeneradasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarListaEstadisticasEncuestasGeneradasOperationCompleted);
            }
            this.InvokeAsync("consultarListaEstadisticasEncuestasGeneradas", new object[] {
                        entidad,
                        identificacion}, this.consultarListaEstadisticasEncuestasGeneradasOperationCompleted, userState);
        }
        
        private void OnconsultarListaEstadisticasEncuestasGeneradasOperationCompleted(object arg) {
            if ((this.consultarListaEstadisticasEncuestasGeneradasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarListaEstadisticasEncuestasGeneradasCompleted(this, new consultarListaEstadisticasEncuestasGeneradasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.id.dc.com", ResponseNamespace="http://www.datacredito.com.co/services/ServicioIdentificacion")]
        [return: System.Xml.Serialization.SoapElementAttribute("adicionarRespuestaCuestionarioReturn")]
        public bool adicionarRespuestaCuestionario(string idRegCuestionario, string nroCuestionario, string nroConValidacion, string cod_pregunta, string cod_respuesta, string orden) {
            object[] results = this.Invoke("adicionarRespuestaCuestionario", new object[] {
                        idRegCuestionario,
                        nroCuestionario,
                        nroConValidacion,
                        cod_pregunta,
                        cod_respuesta,
                        orden});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void adicionarRespuestaCuestionarioAsync(string idRegCuestionario, string nroCuestionario, string nroConValidacion, string cod_pregunta, string cod_respuesta, string orden) {
            this.adicionarRespuestaCuestionarioAsync(idRegCuestionario, nroCuestionario, nroConValidacion, cod_pregunta, cod_respuesta, orden, null);
        }
        
        /// <remarks/>
        public void adicionarRespuestaCuestionarioAsync(string idRegCuestionario, string nroCuestionario, string nroConValidacion, string cod_pregunta, string cod_respuesta, string orden, object userState) {
            if ((this.adicionarRespuestaCuestionarioOperationCompleted == null)) {
                this.adicionarRespuestaCuestionarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnadicionarRespuestaCuestionarioOperationCompleted);
            }
            this.InvokeAsync("adicionarRespuestaCuestionario", new object[] {
                        idRegCuestionario,
                        nroCuestionario,
                        nroConValidacion,
                        cod_pregunta,
                        cod_respuesta,
                        orden}, this.adicionarRespuestaCuestionarioOperationCompleted, userState);
        }
        
        private void OnadicionarRespuestaCuestionarioOperationCompleted(object arg) {
            if ((this.adicionarRespuestaCuestionarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.adicionarRespuestaCuestionarioCompleted(this, new adicionarRespuestaCuestionarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.id.dc.com", ResponseNamespace="http://www.datacredito.com.co/services/ServicioIdentificacion")]
        [return: System.Xml.Serialization.SoapElementAttribute("consultarEstadisticasEncuestasDetalladasReturn")]
        public string consultarEstadisticasEncuestasDetalladas(string xmlEstadisticasDetalladas, string email) {
            object[] results = this.Invoke("consultarEstadisticasEncuestasDetalladas", new object[] {
                        xmlEstadisticasDetalladas,
                        email});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultarEstadisticasEncuestasDetalladasAsync(string xmlEstadisticasDetalladas, string email) {
            this.consultarEstadisticasEncuestasDetalladasAsync(xmlEstadisticasDetalladas, email, null);
        }
        
        /// <remarks/>
        public void consultarEstadisticasEncuestasDetalladasAsync(string xmlEstadisticasDetalladas, string email, object userState) {
            if ((this.consultarEstadisticasEncuestasDetalladasOperationCompleted == null)) {
                this.consultarEstadisticasEncuestasDetalladasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarEstadisticasEncuestasDetalladasOperationCompleted);
            }
            this.InvokeAsync("consultarEstadisticasEncuestasDetalladas", new object[] {
                        xmlEstadisticasDetalladas,
                        email}, this.consultarEstadisticasEncuestasDetalladasOperationCompleted, userState);
        }
        
        private void OnconsultarEstadisticasEncuestasDetalladasOperationCompleted(object arg) {
            if ((this.consultarEstadisticasEncuestasDetalladasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarEstadisticasEncuestasDetalladasCompleted(this, new consultarEstadisticasEncuestasDetalladasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void consultarTiposAlertaCompletedEventHandler(object sender, consultarTiposAlertaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarTiposAlertaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarTiposAlertaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void consultarAlertasCompletedEventHandler(object sender, consultarAlertasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarAlertasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarAlertasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void validarCompletedEventHandler(object sender, validarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void preguntasCompletedEventHandler(object sender, preguntasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class preguntasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal preguntasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void verificarCompletedEventHandler(object sender, verificarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verificarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verificarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void consultarParametroCompletedEventHandler(object sender, consultarParametroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarParametroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarParametroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void consultarParametrizacionCompletedEventHandler(object sender, consultarParametrizacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarParametrizacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarParametrizacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void consultarParametrizacionesCompletedEventHandler(object sender, consultarParametrizacionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarParametrizacionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarParametrizacionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void consultarParametrizacionesCompletasCompletedEventHandler(object sender, consultarParametrizacionesCompletasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarParametrizacionesCompletasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarParametrizacionesCompletasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void consultarCodigosValidacionCompletedEventHandler(object sender, consultarCodigosValidacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarCodigosValidacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarCodigosValidacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void consultarCodigosPreguntasCompletedEventHandler(object sender, consultarCodigosPreguntasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarCodigosPreguntasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarCodigosPreguntasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void consultarParametroParametrizacionesCompletedEventHandler(object sender, consultarParametroParametrizacionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarParametroParametrizacionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarParametroParametrizacionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void consultarParametroParametrizaciones1CompletedEventHandler(object sender, consultarParametroParametrizaciones1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarParametroParametrizaciones1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarParametroParametrizaciones1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void consultarUltimoResultadoCompletedEventHandler(object sender, consultarUltimoResultadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarUltimoResultadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarUltimoResultadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void consultarSistemaAlertasCompletedEventHandler(object sender, consultarSistemaAlertasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarSistemaAlertasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarSistemaAlertasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void consultarEstadisticasDetalladasCompletedEventHandler(object sender, consultarEstadisticasDetalladasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarEstadisticasDetalladasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarEstadisticasDetalladasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void consultarListaEstadisticasGeneradasCompletedEventHandler(object sender, consultarListaEstadisticasGeneradasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarListaEstadisticasGeneradasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarListaEstadisticasGeneradasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void consultarListaEstadisticasEncuestasGeneradasCompletedEventHandler(object sender, consultarListaEstadisticasEncuestasGeneradasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarListaEstadisticasEncuestasGeneradasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarListaEstadisticasEncuestasGeneradasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void adicionarRespuestaCuestionarioCompletedEventHandler(object sender, adicionarRespuestaCuestionarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class adicionarRespuestaCuestionarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal adicionarRespuestaCuestionarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void consultarEstadisticasEncuestasDetalladasCompletedEventHandler(object sender, consultarEstadisticasEncuestasDetalladasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarEstadisticasEncuestasDetalladasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarEstadisticasEncuestasDetalladasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591