//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------




using System.Data.Entity.ModelConfiguration;
using System.Runtime.Serialization;
using Core.Entities;

namespace DataAccess.UserModule.UnitOfWork.Mapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseFieldValueMapping:EntityTypeConfiguration<Core.Entities.SQL.User.BaseFieldValue>
    {
        
        public BaseFieldValueMapping()
        {
                // Primary Key
                this.HasKey(t => t.Id);
    
    
                // Properties
     
                    this.Property(t => t.Value).IsRequired();
    
    
    
                this.ToTable("BaseFieldValue","User");
        this.Property(t => t.Id).HasColumnName("Id");
        this.Property(t => t.BaseFieldId).HasColumnName("BaseFieldId");
        this.Property(t => t.UpdateDate).HasColumnName("UpdateDate");
        this.Property(t => t.UserId).HasColumnName("UserId");
        this.Property(t => t.Value).HasColumnName("Value");
        this.Property(t => t.CollectionNumber).HasColumnName("CollectionNumber");
    
                // Relationships
                this.HasRequired(t => t.BaseField)
                    .WithMany(t => t.BaseFieldValue)
                    .HasForeignKey(d => d.BaseFieldId);
                this.HasRequired(t => t.User)
                    .WithMany(t => t.BaseFieldValue)
                    .HasForeignKey(d => d.UserId);
    
    
    
        }
    
        
        
        
        
        
        
    
        
        
        
    }
}
