//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------




using System.Data.Entity.ModelConfiguration;
using System.Runtime.Serialization;
using Core.Entities;

namespace DataAccess.UserModule.UnitOfWork.Mapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseDataListValueMapping:EntityTypeConfiguration<Core.Entities.SQL.User.BaseDataListValue>
    {
        
        public BaseDataListValueMapping()
        {
                // Primary Key
                this.HasKey(t => t.Id);
    
    
                // Properties
     
                    this.Property(t => t.Value).IsRequired();
    
    
    
                this.ToTable("BaseDataListValue","Req");
        this.Property(t => t.ListId).HasColumnName("ListId");
        this.Property(t => t.Id).HasColumnName("Id");
        this.Property(t => t.Value).HasColumnName("Value");
        this.Property(t => t.IdParent).HasColumnName("IdParent");
        this.Property(t => t.Order).HasColumnName("Order");
    
                // Relationships
                this.HasRequired(t => t.BaseDataList)
                    .WithMany(t => t.BaseDataListValue)
                    .HasForeignKey(d => d.ListId);
    
    
    
        }
    
        
        
        
        
        
    
        
    }
}
