//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------




using System.Data.Entity.ModelConfiguration;

namespace DataAccess.UserModule.UnitOfWork.Mapping
{

    public partial class FieldToCreateUserMapping:EntityTypeConfiguration<Core.Entities.User.FieldToCreateUser>
    {
        
        public FieldToCreateUserMapping()
        {
                // Primary Key
                this.HasKey(t => t.Id);
    
    
                // Properties
     
                    this.Property(t => t.ColumnName).IsRequired()
    .HasMaxLength(50);
    
    
     
                    this.Property(t => t.DataType).IsRequired()
    .HasMaxLength(50);
    
    
    
                this.ToTable("FieldToCreateUser","User");
        this.Property(t => t.Id).HasColumnName("Id");
        this.Property(t => t.BaseFieldId).HasColumnName("BaseFieldId");
        this.Property(t => t.ColumnName).HasColumnName("ColumnName");
        this.Property(t => t.DataType).HasColumnName("DataType");
    
                // Relationships
                this.HasRequired(t => t.BaseField)
                    .WithMany(t => t.FieldToCreateUser)
                    .HasForeignKey(d => d.BaseFieldId);
    
    
    
        }
    
        
        
        
        
    
        
    }
}
