//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Data.DataCredito.WsMotorService
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioMotorPortSoapBinding", Namespace="http://www.datacredito.com.co/services/MotorService")]
    public partial class ServicioMotorService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback consultarBureauOperationCompleted;
        
        private System.Threading.SendOrPostCallback executeStrategyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicioMotorService() {
            this.Url = global::Data.DataCredito.Properties.Settings.Default.Data_DataCredito_WSMotorService_ServicioMotorService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event consultarBureauCompletedEventHandler consultarBureauCompleted;
        
        /// <remarks/>
        public event executeStrategyCompletedEventHandler executeStrategyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.decisor.dc.com", ResponseNamespace="http://www.datacredito.com.co/services/MotorService")]
        [return: System.Xml.Serialization.SoapElementAttribute("consultarBureauReturn")]
        public string consultarBureau(string solicitudBureau, string @params) {
            var results = this.Invoke("consultarBureau", new object[] {
                        solicitudBureau,
                        @params});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultarBureauAsync(string solicitudBureau, string @params) {
            this.consultarBureauAsync(solicitudBureau, @params, null);
        }
        
        /// <remarks/>
        public void consultarBureauAsync(string solicitudBureau, string @params, object userState) {
            if ((this.consultarBureauOperationCompleted == null)) {
                this.consultarBureauOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarBureauOperationCompleted);
            }
            this.InvokeAsync("consultarBureau", new object[] {
                        solicitudBureau,
                        @params}, this.consultarBureauOperationCompleted, userState);
        }
        
        private void OnconsultarBureauOperationCompleted(object arg) {
            if ((this.consultarBureauCompleted != null)) {
                var invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarBureauCompleted(this, new consultarBureauCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.decisor.dc.com", ResponseNamespace="http://www.datacredito.com.co/services/MotorService")]
        [return: System.Xml.Serialization.SoapElementAttribute("executeStrategyReturn")]
        public string executeStrategy(string solicitud) {
            var results = this.Invoke("executeStrategy", new object[] {
                        solicitud});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void executeStrategyAsync(string solicitud) {
            this.executeStrategyAsync(solicitud, null);
        }
        
        /// <remarks/>
        public void executeStrategyAsync(string solicitud, object userState) {
            if ((this.executeStrategyOperationCompleted == null)) {
                this.executeStrategyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexecuteStrategyOperationCompleted);
            }
            this.InvokeAsync("executeStrategy", new object[] {
                        solicitud}, this.executeStrategyOperationCompleted, userState);
        }
        
        private void OnexecuteStrategyOperationCompleted(object arg) {
            if ((this.executeStrategyCompleted != null)) {
                var invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.executeStrategyCompleted(this, new executeStrategyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            var wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void consultarBureauCompletedEventHandler(object sender, consultarBureauCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarBureauCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarBureauCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void executeStrategyCompletedEventHandler(object sender, executeStrategyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class executeStrategyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal executeStrategyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591