//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.UserModule.UnitOfWork
{
    using Core.Entities.SQL.User;
    using System.Data.Entity;
    using DataAccess.UserModule.UnitOfWork.Mapping;
    
    public partial class UserContext : Data.Common.Implementation.UnitOfWork, IUserContext
    {
        public UserContext()
            : base("name=UserModelEntities")
        {
        Database.SetInitializer<UserContext>(null);
        }
    
     
    
        public virtual DbSet<BaseDataList> BaseDataList { get; set; }
        public virtual DbSet<BaseDataListValue> BaseDataListValue { get; set; }
        public virtual DbSet<BaseField> BaseField { get; set; }
        public virtual DbSet<BaseFieldValue> BaseFieldValue { get; set; }
        public virtual DbSet<BaseFile> BaseFile { get; set; }
        public virtual DbSet<FieldToCreateUser> FieldToCreateUser { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
    
    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
         base.OnModelCreating(modelBuilder);
    
        modelBuilder.Configurations.Add(new BaseDataListMapping());
        modelBuilder.Configurations.Add(new BaseDataListValueMapping());
        modelBuilder.Configurations.Add(new BaseFieldMapping());
        modelBuilder.Configurations.Add(new BaseFieldValueMapping());
        modelBuilder.Configurations.Add(new BaseFileMapping());
        modelBuilder.Configurations.Add(new FieldToCreateUserMapping());
        modelBuilder.Configurations.Add(new RoleMapping());
        modelBuilder.Configurations.Add(new UserMapping());
        modelBuilder.Configurations.Add(new UserRoleMapping());
    }
    
    
    }
}
