//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------




using System.Data.Entity.ModelConfiguration;
using Core.Entities.SQL.Process;


namespace DataAccess.ProcessModule.UnitOfWork.Mapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecutionApplicantMapping:EntityTypeConfiguration<Core.Entities.SQL.Process.ExecutionApplicant>
    {
        
        public ExecutionApplicantMapping()
        {
                // Primary Key
                this.HasKey(t => t.Id);
    
    
                // Properties
    
                this.ToTable("ExecutionApplicant","Process");
        this.Property(t => t.Id).HasColumnName("Id");
        this.Property(t => t.RequestId).HasColumnName("RequestId");
        this.Property(t => t.UserId).HasColumnName("UserId");
        this.Property(t => t.IsMain).HasColumnName("IsMain");
        this.Property(t => t.Applicant).HasColumnName("Applicant");
    
                // Relationships
                this.HasRequired(t => t.Execution)
                    .WithMany(t => t.ExecutionApplicant)
                    .HasForeignKey(d => d.RequestId);
    
    
    
        }
    
        
        
        
        
        
    
        
    }
}
