//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------




using System.Data.Entity.ModelConfiguration;
using Core.Entities.Process;


namespace DataAccess.ProcessModule.UnitOfWork.Mapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtendedFileMapping:EntityTypeConfiguration<Core.Entities.Process.ExtendedFile>
    {
        
        public ExtendedFileMapping()
        {
                // Primary Key
                this.HasKey(t => t.Id);
    
    
                // Properties
     
                    this.Property(t => t.Data).IsRequired();
    
    
     
                    this.Property(t => t.FileName).IsRequired()
    .HasMaxLength(2048);
    
    
     
                    this.Property(t => t.Extension).IsRequired()
    .HasMaxLength(32);
    
    
     
                    this.Property(t => t.InternetMimeType).IsRequired()
    .HasMaxLength(256);
    
    
    
                this.ToTable("ExtendedFile","Process");
        this.Property(t => t.Id).HasColumnName("Id");
        this.Property(t => t.Data).HasColumnName("Data");
        this.Property(t => t.FileName).HasColumnName("FileName");
        this.Property(t => t.Extension).HasColumnName("Extension");
        this.Property(t => t.ExtendedFieldValueId).HasColumnName("ExtendedFieldValueId");
        this.Property(t => t.InternetMimeType).HasColumnName("InternetMimeType");
    
                // Relationships
                this.HasRequired(t => t.ExtendedFieldValue)
                    .WithMany(t => t.ExtendedFile)
                    .HasForeignKey(d => d.ExtendedFieldValueId);
    
    
    
        }
    
        
        
        
        
        
        
    
        
    }
}
