//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------




using System.Data.Entity.ModelConfiguration;


namespace DataAccess.ProcessModule.UnitOfWork.Mapping
{

    public partial class ExtendedFieldValueMapping:EntityTypeConfiguration<Core.Entities.Process.ExtendedFieldValue>
    {
        
        public ExtendedFieldValueMapping()
        {
    	this.Map(s => s.MapInheritedProperties());
                // Primary Key
    			
                this.HasKey(t => t.Id);
    
    
                // Properties
    
                this.ToTable("ExtendedFieldValue","Process");
        this.Property(t => t.Id).HasColumnName("Id");
        this.Property(t => t.ExtendedFieldId).HasColumnName("ExtendedFieldId");
        this.Property(t => t.ExecutionId).HasColumnName("ExecutionId");
        this.Property(t => t.Value).HasColumnName("Value");
        this.Property(t => t.UserId).HasColumnName("UserId");
        this.Property(t => t.CollectionNumber).HasColumnName("CollectionNumber");
        this.Property(t => t.Applicant).HasColumnName("Applicant");
    
                // Relationships
                this.HasRequired(t => t.Execution)
                    .WithMany(t => t.ExtendedFieldValue)
                    .HasForeignKey(d => d.ExecutionId);
                this.HasRequired(t => t.ExtendedField)
                    .WithMany(t => t.ExtendedFieldValue)
                    .HasForeignKey(d => d.ExtendedFieldId);
    
    
    
        }
    
        
        
        
        
        
        
        
    
        
        
        
    }
}
