//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------




using System.Data.Entity.ModelConfiguration;
using Core.Entities.SQL.Process;


namespace DataAccess.ProcessModule.UnitOfWork.Mapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageMapping:EntityTypeConfiguration<Core.Entities.SQL.Process.Page>
    {
        
        public PageMapping()
        {
                // Primary Key
                this.HasKey(t => t.Id);
    
    
                // Properties
     
                    this.Property(t => t.Name).IsRequired();
    
    
    
                this.ToTable("Page","Process");
        this.Property(t => t.Id).HasColumnName("Id");
        this.Property(t => t.ProcessId).HasColumnName("ProcessId");
        this.Property(t => t.Name).HasColumnName("Name");
        this.Property(t => t.Order).HasColumnName("Order");
        this.Property(t => t.IsVisible).HasColumnName("IsVisible");
        this.Property(t => t.NameAlias).HasColumnName("NameAlias");
        this.Property(t => t.Enable).HasColumnName("Enable");
    
                // Relationships
                this.HasRequired(t => t.Process)
                    .WithMany(t => t.Page)
                    .HasForeignKey(d => d.ProcessId);
    
    
    
        }
    
        
        
        
        
        
        
        
    
        
        
    }
}
