//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------




using System.Data.Entity.ModelConfiguration;
using Core.Entities.Process;


namespace DataAccess.ProcessModule.UnitOfWork.Mapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebServiceConsultationMapping:EntityTypeConfiguration<Core.Entities.Process.WebServiceConsultation>
    {
        
        public WebServiceConsultationMapping()
        {
    	this.Map(s => s.MapInheritedProperties());
                // Primary Key
    			
                this.HasKey(t => t.Id);
    
    
                // Properties
     
                    this.Property(t => t.WebServiceName).IsRequired()
    .HasMaxLength(500);
    
    
    
                this.ToTable("WebServiceConsultation","Process");
        this.Property(t => t.Id).HasColumnName("Id");
        this.Property(t => t.ExecutionId).HasColumnName("ExecutionId");
        this.Property(t => t.Payload).HasColumnName("Payload");
        this.Property(t => t.WebServiceName).HasColumnName("WebServiceName");
        this.Property(t => t.TypeOfConsultation).HasColumnName("TypeOfConsultation");
        this.Property(t => t.CreatedDate).HasColumnName("CreatedDate");
    
    
        }
    
        
        
        
        
        
        
    }
}
