//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities.SQL.Process
{
    using System;
    using System.Collections.Generic;
    
    public partial class Execution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Execution()
        {
            this.ExecutionApplicant = new HashSet<ExecutionApplicant>();
            this.ExtendedFieldValue = new HashSet<ExtendedFieldValue>();
        }
    
        public long Id { get; set; }
        public int ProcessId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string SimpleId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string ProductData { get; set; }
        public int CurrentStepId { get; set; }
        public int State { get; set; }
        public bool IsActive { get; set; }
        public int CurrentSectionId { get; set; }
        public System.Guid ProductId { get; set; }
    
        public virtual Process Process { get; set; }
        public virtual Section Section { get; set; }
        public virtual Step Step { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExecutionApplicant> ExecutionApplicant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtendedFieldValue> ExtendedFieldValue { get; set; }
    }
}
