//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities.SQL.Process
{
    using System;
    using System.Collections.Generic;
    
    public partial class Step
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Step()
        {
            this.Execution = new HashSet<Execution>();
            this.StepSection = new HashSet<StepSection>();
        }
    
        public int Id { get; set; }
        public int ProcessId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> AutoAdvance { get; set; }
        public string NameClientAlias { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<bool> IsPre { get; set; }
        public Nullable<int> StateId { get; set; }
        public bool Enable { get; set; }
        public int StepType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Execution> Execution { get; set; }
        public virtual Process Process { get; set; }
        public virtual State State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StepSection> StepSection { get; set; }
    }
}
