//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Process
{

    public partial class ExecutionApplicant
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }
        public long ExecutionId { get; set; }
        public long UserId { get; set; }
        public bool IsMain { get; set; }
        public int Applicant { get; set; }
    
        public virtual Execution Execution { get; set; }
    }
}
