//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities.Process
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecutionStep
    {
        public long Id { get; set; }
        public long ExecutionId { get; set; }
        public int StepId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long UserId { get; set; }
    
        public virtual Execution Execution { get; set; }
        public virtual Step Step { get; set; }
    }
}
