//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities.Process
{
    using System.Collections.Generic;

    public partial class ExtendedFieldValue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExtendedFieldValue()
        {
            this.ExtendedFile = new HashSet<ExtendedFile>();
        }
    
        public long Id { get; set; }
        public int ExtendedFieldId { get; set; }
        public long ExecutionId { get; set; }
        public byte[] Value { get; set; }
        public long UserId { get; set; }
        public int CollectionNumber { get; set; }
        public int Applicant { get; set; }
    
        public virtual Execution Execution { get; set; }
        public virtual ExtendedField ExtendedField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtendedFile> ExtendedFile { get; set; }
    }
}
