//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Banlinea.ProcessFlow.Model;

namespace Core.Entities.Process
{

    public partial class FieldInSection:FieldInSectionFlow
    {
        public override int Id { get; set; }
        public int ExtendedFieldId { get; set; }
        public override int SectionId { get; set; }
        public override int Order { get; set; }
        public override bool IsVisible { get; set; }
        public override bool IsReadOnly { get; set; }
        public override bool IsRequired { get; set; }
        public override int Applicant { get; set; }
    
        public virtual ExtendedField ExtendedField { get; set; }
        public virtual Section Section { get; set; }
    }
}
