//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities.Process
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldInSection
    {
        public int Id { get; set; }
        public int ExtendedFieldId { get; set; }
        public int SectionId { get; set; }
        public int Order { get; set; }
        public bool IsVisible { get; set; }
        public bool IsReadOnly { get; set; }
        public bool IsRequired { get; set; }
        public int Applicant { get; set; }
    
        public virtual ExtendedField ExtendedField { get; set; }
        public virtual Section Section { get; set; }
    }
}
